name: Build Release CUDA
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '2021.12.03'
      release_name:
        description: 'Release Name'
        required: true
        default: '2021.12.03 "Chen" Release'
jobs:
  windows_build:
    strategy:
      matrix:
        arch: [ 52 60 70 72 75 80 ]
      fail-fast: false
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - name: Install Zlib
      run: |
        powershell -Command "(Invoke-WebRequest -Uri https://git.io/JnHTY -OutFile install_zlib.bat)"; ./install_zlib.bat; del install_zlib.bat
        del "C:/Program Files/zlib/lib/zlib.lib"
        del "C:/Program Files/zlib/bin/zlib.dll"
    - name: Install Cuda
      uses: Jimver/cuda-toolkit@v0.2.5
    - name: Install Ninja and CMake
      run: |    
        choco install ninja cmake
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.0
        modules: addons.qtcharts qtopengl    
    - name: get TIPL and DSI Studio atlas
      run: |
        git clone https://github.com/frankyeh/TIPL.git
        git clone https://github.com/frankyeh/DSI-Studio-atlas.git
    - name: Build DSI Studio
      run: |
        for /f "usebackq delims=#" %%a in (`"%programfiles(x86)%\Microsoft Visual Studio\Installer\vswhere" -latest -property installationPath`) do call "%%a\Common7\Tools\VsDevCmd.bat" -arch=x64
        mkdir -p build
        cmake -S . -B build -GNinja "-DCMAKE_BUILD_TYPE:STRING=Release" "-DCMAKE_C_COMPILER:STRING=cl" "-DCMAKE_CXX_COMPILER:STRING=cl" -DCUDA_aRCH=${{ matrix.arch }} -DTIPL_DIR=. "-DCMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /GR /EHsc -DQT_QML_DEBUG" "-DCMAKE_CXX_FLAGS_DEBUG:STRING=/Zi /Ob0 /Od /RTC1 -DQT_QML_DEBUG" "-DCMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/Zi /O2 /Ob1 /DNDEBUG -DQ_QML_DEBUG"
        cmake --build ./build --parallel --config Release
      shell: cmd

    - name: Packaging
      run: |
        mkdir dsi_studio_win
        move other\color_map dsi_studio_win   
        move other\LICENSE dsi_studio_win   
        move other\device.txt dsi_studio_win   
        move build\dsi_studio.exe dsi_studio_win
        windeployqt --no-translations --no-system-d3d-compiler --compiler-runtime --no-opengl-sw dsi_studio_win\dsi_studio.exe
        move DSI-Studio-atlas dsi_studio_win\atlas  
    - name: Download TinyFSL
      uses: suisei-cn/actions-download-file@v1
      with:
        url: "https://github.com/frankyeh/TinyFSL/releases/download/2021.12.03/tiny_fsl_win64.zip"
    - name: Extract zip files
      run: |
        7z e tiny_fsl_win64.zip -odsi_studio_win\plugin
        rd dsi_studio_win\plugin\tiny_fsl
        del *.zip
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.6.0
      with:
        filename: dsi_studio_win_cuda_SM${{ matrix.arch }}.zip
        exclusions: .git
        path: dsi_studio_win
    - name: Create Release
      uses: ncipollo/release-action@v1.8.9
      with:
        allowUpdates: true
        artifacts: "*.zip"
        tag: ${{ github.event.inputs.tag }}
        name: ${{ github.event.inputs.release_name }}
        prerelease: false  
