name: Test Release 
on:
  workflow_run:
    workflows: [Build Release]
    types: [completed]
    
  workflow_dispatch:
jobs:
  Animal_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://zenodo.org/record/6321169/files/mountsinai-S-sub-032156_dwi.src.gz?download=1 -o Rhesus.src.gz
        chmod 777 ./dsi-studio/dsi_studio
    - name: Test DTI/GQI Recon
      run: |  
        ./dsi-studio/dsi_studio --source=*.src.gz --action=rec --method=1 |& tee -a log.txt
        ls Rhesus.src.gz.dti.fib.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=*.src.gz --action=rec |& tee -a log.txt
        ls Rhesus.src.gz.gqi.1.25.fib.gz

    
  Human_Recon:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://zenodo.org/record/6320992/files/20081006_M025Y_DSI_203.src.gz?download=1 -o DSI.src.gz
        curl -L https://zenodo.org/record/6320992/files/20081006_M025Y_DTI64.src.gz?download=1 -o DTI.src.gz
        curl -L https://zenodo.org/record/6320992/files/20081006_M025Y_HARDI.src.gz?download=1 -o HARDI.src.gz
        chmod 777 ./dsi-studio/dsi_studio
    - name: Test GQI Recon
      run: |
        ./dsi-studio/dsi_studio --source=*.src.gz --action=rec --method=1
        ls DSI.src.gz.dti.fib.gz 
        ls DTI.src.gz.dti.fib.gz 
        ls HARDI.src.gz.dti.fib.gz 
        ./dsi-studio/dsi_studio --source=*.src.gz --action=rec
        ls DSI.src.gz.gqi.1.25.fib.gz
        ls DTI.src.gz.gqi.1.25.fib.gz
        ls HARDI.src.gz.gqi.1.25.fib.gz
        ./dsi-studio/dsi_studio --source=*.src.gz --action=rec --method=7 --template=0
        ls DSI.src.gz.icbm152.qsdr.1.25.*
        ls DTI.src.gz.icbm152.qsdr.1.25.*
        ls HARDI.src.gz.icbm152.qsdr.1.25.*
        
  Human_Tracking_QSDR:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://github.com/frankyeh/DSI-Studio-atlas/blob/main/ICBM152/ICBM152.fib.gz?raw=true -o ICBM152.fib.gz
        chmod 777 ./dsi-studio/dsi_studio
    - name: Tracking
      run: |
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --output=icbm152.tt.gz --export=stat,tdi
        ls icbm152.tt.gz
        ls icbm152.tt.gz.tdi.nii.gz
        ls icbm152.tt.gz.stat.txt
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --track_id=Arcuate_Fasciculus_L --output=AF_L.tt.gz
        ls AF_L.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --roi=FreeSurferDKT_Cortical:left_precentral,dilate,dilate,smoothing --roi2=FreeSurferDKT_Cortical:right_precentral,dilate,dilate,smoothing --output=LR.tt.gz
        ls LR.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=ICBM152.fib.gz --action=trk --fiber_count=1000000 --output=no_file --connectivity=FreeSurferDKT_Cortical --connectivity_value=count,qa
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.connectivity.mat
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.connectogram.txt
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.network_measures.txt
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.connectivity.mat
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.connectogram.txt
        ls ICBM152.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.network_measures.txt

  Human_Tracking_GQI:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://zenodo.org/record/6307812/files/100206.src.gz.gqi.1.7.fib.gz?download=1 -o 100206.fib.gz
        curl -L https://github.com/frankyeh/DSI-Studio-atlas/blob/main/ICBM152/ICBM152.QA.nii.gz?raw=true -o template_qa.nii.gz
        chmod 777 ./dsi-studio/dsi_studio
    - name: Tracking
      run: |
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --output=100206.tt.gz --export=stat,tdi
        ls 100206.tt.gz
        ls 100206.tt.gz.tdi.nii.gz
        ls 100206.tt.gz.stat.txt
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --track_id=Arcuate_Fasciculus_L --output=AF_L.tt.gz
        ls AF_L.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --roi=FreeSurferDKT_Cortical:left_precentral,dilate,dilate,smoothing --roi2=FreeSurferDKT_Cortical:right_precentral,dilate,dilate,smoothing --output=LR.tt.gz
        ls LR.tt.gz
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --fiber_count=1000000 --output=no_file --connectivity=FreeSurferDKT_Cortical --connectivity_value=count,qa
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.connectivity.mat
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.connectogram.txt
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.count.pass.network_measures.txt
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.connectivity.mat
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.connectogram.txt
        ls 100206.fib.gz.tt.gz.FreeSurferDKT_Cortical.qa.pass.network_measures.txt
        echo --------------------------------------------------------------------------------------------------
        ./dsi-studio/dsi_studio --source=100206.fib.gz --action=trk --other_slices=template_qa.nii.gz --dt_threshold_index=template_qa-qa --seed_count=1000000 --dt_threshold=0.1 --output=dt.tt.gz
        ls dt.tt.gz


  Connectometry:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://zenodo.org/record/6324701/files/CMU60.db.fib.gz?download=1 -o CMU60.db.fib.gz
        curl -L https://zenodo.org/record/6324701/files/CMU60.demo.csv?download=1 -o CMU60.demo.csv
        chmod 777 ./dsi-studio/dsi_studio
    - name: Connectometry
      run: |
        cat CMU60.demo.csv
        ./dsi-studio/dsi_studio --source=CMU60.db.fib.gz --action=cnt --demo=CMU60.demo.csv --t_threshold=2.5 --permutation=200 --variable_list=0,1 --voi=1
        ls * -l
        
  Automatic_Tracking:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      run: |
        curl -L "https://github.com/frankyeh/DSI-Studio/releases/download/2021.12.03/dsi_studio_ubuntu_2004.zip" | jar xv
        curl -L https://zenodo.org/record/6307812/files/100206.src.gz.gqi.1.7.fib.gz?download=1 -o 100206.fib.gz
        curl -L https://zenodo.org/record/6307812/files/100307.src.gz.gqi.1.7.fib.gz?download=1 -o 100307.fib.gz
        curl -L https://zenodo.org/record/6307812/files/100408.src.gz.gqi.1.7.fib.gz?download=1 -o 100408.fib.gz
        chmod 777 ./dsi-studio/dsi_studio
    - name: Tracking
      run: |
        ./dsi-studio/dsi_studio --source=*.fib.gz --action=atk --track_id=Optic,Arcuate,spinal
        ls Arcuate_Fasciculus_L.stat.txt
        ls Arcuate_Fasciculus_R.stat.txt
        ls Optic_Radiation_L.stat.txt
        ls Optic_Radiation_R.stat.txt
        ls Corticospinal_Tract_L.stat.txt
        ls Corticospinal_Tract_R.stat.txt

